### ISSUE TITLE
Looking for paper link

### ISSUE THREAD

**Issue by echo-sky** [Evarray/LFG-Net#1]
Hello,
 I can't search the paper corresponding to the code.
 Could you send me or make it public in arXiv.
 Many thanks.
 Looking forward to hearing from you.

**Comment by Evarray** [comment]
Hi,
Our paper is accepted by IEEE Transactions on Geoscience and Remote Sensing at present. The early access version will coming soon, and the link will be given later.
Many Thanks.

**Comment by Evarray** [comment]
> Hello, I can't search the paper corresponding to the code. Could you send me or make it public in arXiv. Many thanks. Looking forward to hearing from you.

Hi,
Our paper is accepted by IEEE Transactions on Geoscience and Remote Sensing at present. The early access version will coming soon, and the link will be given later.
Many Thanks.

**Comment by Evarray** [comment]
> Hello, I can't search the paper corresponding to the code. Could you send me or make it public in arXiv. Many thanks. Looking forward to hearing from you.

The paper corresponding to the code is released at: https://ieeexplore.ieee.org/abstract/document/9815311. 
Hope it helps your work.
